add login instructions for regular users
matrixone-cloud/moc-docs pull request #230
Opened 2024-01-09 09:57 UTC by yangj1211

#225

2024-01-09 09:58 UTC, yangj1211 commented
@dengn need to review

2024-01-10 13:11 UTC, dengn requested changes
不要在这里改这个流程，这里就只写默认的admin登陆流程就好了。不然用户上来就follow一个很复杂的流程，反而会搞得很麻烦。
应该是：在现在这篇文档里说明清楚默认是由admin来登陆的，然后也同样可以支持用普通用户来登陆，另外专门写一篇文档做说明，再链接过去。

2024-01-11 07:08 UTC, yangj1211 commented
@dengn need to review 

说明更新至目录“安全-身份访问控制”处

2024-01-12 06:22 UTC, dengn requested changes

2024-01-12 06:22 UTC, dengn commented on docs/MatrixOne-Cloud/Security/Security-Permission-Overview.md
> +
不要含在这个文档里，单独起一篇文章。这应该是一篇非常独立的教程类的文档，而不是混在overview的文档里。

2024-01-12 07:03 UTC, yangj1211 commented
@dengn need to review

2024-01-15 07:01 UTC, dengn requested changes
还要继续优化下页面访问逻辑

2024-01-15 10:55 UTC, yangj1211 commented
@dengn need to review

2024-01-15 14:56 UTC, dengn requested changes

2024-01-15 14:56 UTC, dengn commented on docs/MatrixOne-Cloud/Instance-Mgmt/login-instance.md
> +
关于admin/普通用户的说明，需要给个链接到相应的文档里。

2024-01-16 03:31 UTC, yangj1211 commented
@dengn need to review

2024-01-16 08:35 UTC, merged