add dof of MOne
matrixone-cloud/moc-docs pull request #236
Opened 2024-01-25 06:47 UTC by yangj1211

#220

2024-01-25 06:48 UTC, yangj1211 commented
@dengn need to review

2024-01-29 01:20 UTC, dengn requested changes

2024-01-29 01:20 UTC, dengn commented on docs/MatrixOne-Cloud/Overview/mone-introduction.md
> +AI 框架我们采用的是 LangChain，Embedding 使用了 OpenAI Embedding 模型，OpenAI LLM 大模型使用的是 GPT-3.5-Turbo。OpenAI embedding 调用 MatrixOne 接口，基于向量化能力完成向量存储和相似度搜索，收集相似度最高的文本，调用 GPT 3.5 模型提炼优化文本，最终得到最为贴近的答案。
“OpenAI embedding 调用 MatrixOne 接口” 这句话写的不对。是MOC调用的OpenAI embedding接口。

2024-01-29 02:22 UTC, yangj1211 commented
@dengn need to review

2024-01-29 10:43 UTC, dengn approved these changes

2024-01-29 10:43 UTC, merged