add description for load_data_local
matrixone-cloud/moc-docs pull request #251
Opened 2024-01-31 08:24 UTC by yangj1211

#240

2024-02-01 06:41 UTC, dengn requested changes

2024-02-01 06:41 UTC, dengn commented on docs/MatrixOne-Cloud/App-Develop/import-data/bulk-load/bulk-load-overview.md
> +MatrixOne 支持使用 `LOAD DATA` 命令将大量行插入至 MatrixOne 数据表，对于 MatrixOne Clound 的实例若需要导入本地数据，可使用 `LOAD DATA LOCAL` 命令，也支持使用 `SOURCE` 命令将表结构和数据导入整个数据库。
typo错误Clound

2024-02-01 08:37 UTC, yangj1211 commented
@dengn need to review

2024-02-04 07:39 UTC, dengn approved these changes

2024-02-04 07:39 UTC, merged