load data unsupport tar
matrixone-cloud/moc-docs pull request #276
Opened 2024-03-04 03:32 UTC by yangj1211

#275

2024-03-04 03:35 UTC, yangj1211 commented
[#14485](https://github.com/matrixorigin/matrixone/issues/14485)
@dengn need to review

2024-03-04 06:59 UTC, dengn requested changes

2024-03-04 06:59 UTC, dengn commented on docs/MatrixOne-Cloud/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
> +!!! note
支持啥格式的也要注明一下

2024-03-06 09:55 UTC, dengn approved these changes

2024-03-06 09:55 UTC, merged