Update mysql-compatibility.md
matrixone-cloud/moc-docs pull request #56
Opened 2023-11-07 01:17 UTC by WuMenglong

Modify a description about the Account.

2023-11-07 06:24 UTC, dengn requested changes

2023-11-07 06:24 UTC, dengn commented on docs/MatrixOne-Cloud/Overview/mysql-compatibility.md
> +- MatrixOne Cloud 中无单独 ACCOUNT 概念，在 MatrixOne Cloud 中创建的每个实例都是一个单独的租户。
可以改成：与 MatrixOne 内核不同，MatrixOne Cloud 中无单独 ACCOUNT 概念，在 MatrixOne Cloud 的一个 Region 中创建的每个实例都属于一个 MatrixOne 分布式集群，其中的每个实例其实都是集群中单独的 ACCOUNT ，无法在 MatrixOne Cloud 实例中再继续创建 ACCOUNT。

2023-11-08 02:20 UTC, WuMenglong commented on docs/MatrixOne-Cloud/Overview/mysql-compatibility.md
> +- MatrixOne Cloud 中无单独 ACCOUNT 概念，在 MatrixOne Cloud 中创建的每个实例都是一个单独的租户。
already edited

2023-11-08 05:58 UTC, dengn approved these changes

2023-11-08 05:59 UTC, merged